### ISSUE TITLE
Add Activities to MicroByte on Memory Leak

### ISSUE THREAD

**Issue by sudiptog81** [Crio-Bytes/OS#2]
**MicroByte Title:** Memory Leak

**Improvement Proposal:** 

- Addition of Programs written in C to demonstrate memory leaks
- Addition of Engaging Activities involving debugging, looking at logs

**Benefits of proposed improvements:** 

Learners will be able to grasp the concepts better when they perform simple activities rather than reading through a tutorial.

**Comment by amoghrajesh** [comment]
@sudiptog81 you can start working on this. 
Keep in mind the structure and learn by doing methodology.
All the best!
